parameters:
#    burgeap_admin.example.class: Burgeap\AdminBundle\Example

services:
#    burgeap_admin.example:
#        class: %burgeap_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
